name: Flat Earth
favicon: null
layout_spectrum: 0.02305460744537413
typography_spectrum: 0.5871876084711403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7438628450036049
  lightness: 0.7897955481894314
  saturation: 0.20709050819277763
  rhythmicContrast: 0.8160826929379255
purpose: []
