name: Flat Earth
favicon: null
layout_spectrum: 0
typography_spectrum: 0.76045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11221a'
    - '#c8d6b2'
    - '#c68545'
    - '#4c7e43'
    - '#875032'
  brandStrength: 0
  lightness: 0.7897955481894314
  saturation: 0.5
  rhythmicContrast: 0.8160826929379255
purpose: []
