name: Flat Earth
favicon: null
layout_spectrum: 0.2637
typography_spectrum: 0.76045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e9d3'
    - '#b7b491'
    - '#51491b'
    - '#291e0a'
    - '#8a8132'
  brandStrength: 1
  lightness: 0.7897955481894314
  saturation: 0.5
  rhythmicContrast: 0.8160826929379255
purpose: []
